AWSTemplateFormatVersion: '2010-09-09'
Description: "ECR resources stack"

Parameters:
  Env:
    Type: String
    AllowedValues: [ "dev", "qa", "prod" ]
    Default: "dev"
    Description: "Entorno de despliegue. Ejemplo: dev, qa, prod"
  RepoName:
    Type: String
    Description: "Nombre del repositorio de GitHub. Ejemplo: my-repo"

Resources:

  EcrRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RepositoryName: !Sub "${RepoName}-${Env}"

Outputs:
  ExportedECRRepositoryArn:
    Value: !GetAtt EcrRepository.Arn
    Description: "ARN del repositorio ECR creado"
  ExportedEcrRepositoryName:
    Value: !Sub "${RepoName}-${Env}"
    Description: "Nombre del repositorio ECR creado"
